name: 'Composer install'
description: 'Install composer dependencies'

inputs:
  php-version:
    description: 'PHP version'
    required: true

  composer-flags:
    description: 'Flags to use when installing composer dependencies.'
    required: false
    default: ''

outputs:
  image:
    description: 'The image name that was used to setup composer dependencies. Can be used in subsequent jobs.'
    value: ${{ steps.composer.outputs.image }}

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/composer-install@v4
      id: composer
      with:
        php-version: ${{ inputs.php-version }}
        flags: ${{ inputs.composer-flags }}
