name: 'Yarn install'
description: 'Install yarn dependencies'

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/yarn-install@v4
      with:
        node-version: ${{ vars.NODE_VERSION }}

    - name: 'Import translations'
      shell: bash
      #language=sh
      run: |
        yarn translations:import
