name: 'Yarn install'
description: 'Install yarn dependencies'

inputs:
  node-version:
    description: 'Node version'
    required: true

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/yarn-install@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}

    - name: 'Import translations'
      shell: bash
      #language=sh
      run: |
        yarn translations:import
