name: 'Setup'
description: 'Install dependencies'

inputs:
  node-version:
    description: 'Node version'
    required: true

  php-version:
    description: 'PHP version'
    required: true

  composer-flags:
    description: 'Flags to use when installing composer dependencies.'
    required: false
    default: ''

outputs:
  image:
    description: 'The image name that was used to setup composer dependencies. Can be used in subsequent jobs.'
    value: ${{ steps.composer.outputs.image }}

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/composer-install@v4
      id: composer
      with:
        php-version: ${{ inputs.php-version }}
        flags: ${{ inputs.composer-flags }}

    - uses: myparcelnl/actions/yarn-install@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: 'Import translations'
      shell: bash
      #language=bash
      run: |
        yarn translations:import
