import {executePdkComponentTests} from '@myparcel-pdk/admin-component-tests';
import {
  WcBox,
  WcButton,
  WcButtonGroup,
  WcCheckboxGroup,
  WcCheckboxInput,
  WcCol,
  WcDropdownButton,
  WcFormGroup,
  WcImage,
  WcModal,
  WcNotification,
  WcPluginSettingsWrapper,
  WcRadioInput,
  WcRow,
  WcSelectInput,
  WcTabNavButton,
  WcTabNavButtonWrapper,
  WcTable,
  WcTableCol,
  WcTableRow,
  WcTextInput,
  WcToggleInput,
} from '../components/pdk';

executePdkComponentTests({
  Box: WcBox,
  Button: WcButton,
  ButtonGroup: WcButtonGroup,
  CheckboxGroup: WcCheckboxGroup,
  CheckboxInput: WcCheckboxInput,
  Col: WcCol,
  DropdownButton: WcDropdownButton,
  FormGroup: WcFormGroup,
  Image: WcImage,
  Modal: WcModal,
  Notification: WcNotification,
  PluginSettingsWrapper: WcPluginSettingsWrapper,
  RadioInput: WcRadioInput,
  Row: WcRow,
  SelectInput: WcSelectInput,
  TabNavButton: WcTabNavButton,
  TabNavButtonWrapper: WcTabNavButtonWrapper,
  Table: WcTable,
  TableCol: WcTableCol,
  TableRow: WcTableRow,
  TextInput: WcTextInput,
  ToggleInput: WcToggleInput,
});
