name: 'Feature request'
description: 'Suggest an idea to improve the plugin.'
labels: [ 'feature' ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form! We will respond as fast as we can. Don't forget to check
        whether your issue might be a duplicate of an existing one before submitting.

  - type: textarea
    attributes:
      label: 'What problem does this feature solve?'
      description: 'Explain why this feature should be added.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'What should the solution look like?'
      description: 'Describe how you would like above problem to be solved.'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 'Relevant log output'
      description: 'Copy and paste any relevant log output here. Proper formatting will be applied automatically.'
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context'
      description: |
        Add any other context or screenshots about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
