name: 'Install'
description: 'Install dependencies using cache'

outputs:
  image:
    description: 'The image name that was used to install composer dependencies. Can be used in subsequent jobs.'
    value: ${{ steps.composer.outputs.image }}

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/composer-install@v3
      id: composer
      with:
        php-version: 7.4

    - uses: myparcelnl/actions/yarn-install@v3
      with:
        node-version: 18
