name: '🔸 Rebase pull requests'

on:
  workflow_call:

jobs:
  rebase:
    name: 'Rebase pull requests to develop'
    runs-on: ubuntu-22.04
    steps:
      - uses: peter-evans/rebase@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          base: develop
          exclude-drafts: true
          exclude-labels: 'hotfix'
