name: '🔸 Test'

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/install

  test-frontend:
    needs: install
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/install

      - uses: ./.github/actions/test-frontend

  test-backend:
    needs: install
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/install
        id: install

      - uses: ./.github/actions/test-backend
        with:
          image: ${{ steps.install.outputs.image }}
