name: '♻️ Analyse'

on:
  workflow_call:
    inputs:
      ref:
        description: 'Ref to run on'
        type: string
        required: false
        default: ${{ github.ref }}

jobs:
  analyse:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: 'Handle PHPStan cache'
        uses: actions/cache@v4
        id: phpstan-cache
        with:
          path: './.tmp/phpstan'
          key: phpstan-cache-${{ hashFiles('phpstan.neon.dist', 'composer.json') }}-${{ hashFiles('**/*.php') }}
          restore-keys: |
            phpstan-cache-${{ hashFiles('phpstan.neon.dist', 'composer.json') }}-
            phpstan-cache-

      - uses: myparcelnl/actions/pdk-setup-upgrade@v4
        if: steps.phpstan-cache.outputs.cache-hit != 'true'
        id: setup
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          php-version: ${{ vars.PHP_VERSION }}
          mode: 'backend'

      - name: 'Run PHPStan analysis'
        if: steps.phpstan-cache.outputs.cache-hit != 'true'
        env:
          IMAGE: ${{ steps.setup.outputs.image }}
        shell: bash
        #language=bash
        run: |
          docker run -t \
            --volume $PWD:/app \
            $IMAGE \
            php -dmemory_limit=-1 vendor/bin/phpstan \
              analyse \
              --no-progress \
              --no-interaction
