name: '♻️ Analyse'

on:
  workflow_call:

jobs:
  analyse:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: myparcelnl/actions/setup-git-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.credentials.outputs.token }}

      - name: 'Handle PHPStan cache'
        uses: actions/cache@v3
        id: phpstan-cache
        with:
          path: './.tmp/phpstan'
          key: phpstan-cache-${{ hashFiles('phpstan.neon.dist', 'composer.json') }}-${{ hashFiles('**/*.php') }}
          restore-keys: |
            phpstan-cache-${{ hashFiles('phpstan.neon.dist', 'composer.json') }}-
            phpstan-cache-

      - uses: ./.github/actions/composer-install

      - name: 'Run PHPStan analysis'
        if: steps.phpstan-cache.outputs.cache-hit != 'true'
        shell: bash
        #language=sh
        run: |
          docker run -t \
            --volume $PWD:/app \
            ${{ steps.setup.outputs.image }} \
            php -dmemory_limit=-1 vendor/bin/phpstan \
              analyse \
              --no-progress \
              --no-interaction
