name: '🔨 Build with custom pdk versions'
run-name: 'Build with pdk@${{ inputs.php-pdk-ref }} and js-pdk@${{ inputs.js-pdk-ref }}'

on:
  workflow_dispatch:
    inputs:
      php-pdk-ref:
        default: 'main'
        description: 'Ref of myparcelnl/pdk to use'

      js-pdk-ref:
        default: 'main'
        description: 'Ref of myparcelnl/js-pdk to use'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}-${{ inputs.php-pdk-ref }}-${{ inputs.js-pdk-ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/pdk-custom-build@v4
        id: prepare
        with:
          php-version: ${{ vars.PHP_VERSION }}
          php-scoper-version: ${{ vars.PHP_SCOPER_VERSION }}
          js-pdk-ref: ${{ inputs.js-pdk-ref }}
          php-pdk-ref: ${{ inputs.php-pdk-ref }}
          source-files: |
            src/**/*
            config/**/*
            scoper.inc.php
            woocommerce-myparcel.php

      - uses: lhotari/action-upterm@v1
        if: failure()
        with:
          limit-access-to-actor: true
          wait-timeout-minutes: 5
