name: '⚙️ On pull request'

on:
  pull_request:
    branches:
      - alpha
      - beta

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
