name: 'Post PR Artifacts'

on:
  workflow_run:
    types:
      - completed

    workflows:
      - '⚙️ On pull request'

run-name: 'Post artifacts on PR #${{ github.event.workflow_run.pull_requests[0].number }}'

jobs:
  post-pr-artifacts:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/pr-post-artifacts@v4
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
