name: 'Post PR Artifacts'

on:
  workflow_run:
    types:
      - completed

    workflows:
      - '⚙️ On pull request'

jobs:
  post-pr-artifacts:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/pr-post-artifacts@v4
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
