name: '⚙️ On pull request'

on:
  pull_request:
    branches:
      - alpha
      - beta

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  analyse:
    uses: ./.github/workflows/analyse.yml
    secrets: inherit

  build:
    runs-on: ubuntu-22.04
    needs:
      - test
      - analyse
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: ./.github/actions/build
        id: build
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - name: 'Determine version'
        id: version
        #language=sh
        run: |
          version=$(npm pkg get version | sed 's/"//g') 
          releaseVersion="$version-${{ github.event.pull_request.number}}.${{ github.event.pull_request.head.sha }}"

          echo "version=$releaseVersion" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/release
        id: release
        with:
          version: ${{ steps.version.outputs.version }}
