name: '⚙️ On pull request'

on:
  pull_request:
    branches:
      - main
      - beta
      - alpha

  repository_dispatch:
    types: [trigger-pr-build]

run-name: 'PR #${{ github.event.client_payload.number || github.event.pull_request.number }}'

concurrency:
  group: '${{ github.workflow }}-${{ github.event.client_payload.number || github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      ref: ${{ github.event.client_payload.ref || github.ref }}

  analyse:
    uses: ./.github/workflows/analyse.yml
    secrets: inherit
    with:
      ref: ${{ github.event.client_payload.ref || github.ref }}

  build:
    runs-on: ubuntu-22.04
    # Create build for pr even if checks fail
    if: always()
    needs:
      - test
      - analyse
    steps:
      - uses: myparcelnl/actions/pdk-prerelease@v5
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          ref: ${{ github.event.client_payload.ref || github.ref }}
          pr-number: ${{ github.event.client_payload.number || github.event.pull_request.number }}
          php-version: ${{ vars.PHP_VERSION }}
          php-scoper-version: ${{ vars.PHP_SCOPER_VERSION }}
          source-files: |
            src/**/*
            config/**/*
            scoper.inc.php
            woocommerce-myparcel.php
