name: '⚙️ On pull request'

on:
  pull_request:
    branches:
      - alpha
      - beta

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  analyse:
    uses: ./.github/workflows/analyse.yml
    secrets: inherit

  build:
    runs-on: ubuntu-22.04
    needs:
      - test
      - analyse
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.credentials.outputs.token }}

      - uses: ./.github/actions/setup
        with:
          composer-flags: --no-dev

      - uses: ./.github/actions/build

      - name: 'Determine version'
        id: version
        run: |
          version="$(npm pkg get version)-${{ github.event.pull_request.number}}.${{ github.event.pull_request.head.sha }}"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: 'Create release packages'
        #language=sh
        run: |
          yarn pdk-builder release --version ${{ steps.version.outputs.version }} -vvv

      - name: 'Upload build artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ steps.version.outputs.version }}
          path: |
            dist/*.zip
