name: '⚙️ On pull request'

on:
  pull_request:
    branches:
      - alpha
      - beta

  repository_dispatch:
    types: [trigger-pr-build]

run-name: 'PR #${{ github.event.client_payload.number || github.event.pull_request.number }}'

concurrency:
  group: '${{ github.workflow }}-${{ github.event.client_payload.number || github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      ref: ${{ github.event.client_payload.ref || github.ref }}

  analyse:
    uses: ./.github/workflows/analyse.yml
    secrets: inherit
    with:
      ref: ${{ github.event.client_payload.ref || github.ref }}

  build:
    runs-on: ubuntu-22.04
    needs:
      - test
      - analyse
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref || github.ref }}

      - uses: ./.github/actions/build
        id: build
        with:
          node-version: ${{ vars.NODE_VERSION }}
          php-version: ${{ vars.PHP_VERSION }}
          composer-flags: '--no-dev'
          php-scoper-version: ${{ vars.PHP_SCOPER_VERSION }}

      - uses: myparcelnl/actions/pdk-prerelease-pr@v4
        with:
          image: ${{ steps.build.outputs.image }}
          pr-number: ${{ github.event.client_payload.number || github.event.pull_request.number }}
