name: '♻️ Rebase PRs'

on:
  workflow_call:

jobs:
  rebase-prs:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/rebase-prs@v4
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          base: ${{ github.ref_name }}
          exclude-drafts: true
          exclude-labels: 'dependencies'
