name: '🧩 Rebase branches'

on:
  workflow_call:
    inputs:
      base:
        type: string
        required: true

      target:
        type: string
        required: true

      force:
        type: boolean
        required: false
        default: false

  workflow_dispatch:
    inputs:
      base:
        type: string
        description: 'Base branch'
        required: true
        default: 'develop'

      target:
        type: string
        description: 'Target branch to update'
        required: true
        default: 'main'

      force:
        type: boolean
        description: 'Force push target branch'
        required: false
        default: false

jobs:
  rebase:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v4
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: myparcelnl/actions/rebase@v4
        with:
          token: ${{ steps.credentials.outputs.token }}
          base: ${{ inputs.base || github.ref_name }}
          target: ${{ inputs.target }}
          force: ${{ inputs.force }}
