name: '🚀 Release RC'

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  release:
    name: 'Release'
    uses: ./.github/workflows/--release.yml
    secrets: inherit

  rebase-prs:
    name: 'Rebase pull requests'
    uses: ./.github/workflows/--rebase-prs.yml
    secrets: inherit
    needs: release
    if: always()
