name: '🧪 Run tests'

on:
  workflow_call:
    inputs:
      ref:
        description: 'Ref to run on'
        type: string
        required: false
        default: ${{ github.ref }}

jobs:
  test-frontend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: 'Cache coverage'
        uses: actions/cache@v4
        id: coverage-cache
        with:
          key: coverage-frontend-${{ hashFiles('**/package.json', '**/yarn.lock', 'views/**/*') }}
          path: coverage/views

      - uses: myparcelnl/actions/pdk-setup-frontend@v4
        if: steps.coverage-cache.outputs.cache-hit != 'true'

      - uses: myparcelnl/actions/pdk-upgrade@v4
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          report: 'false'
          no-check: true
          no-commit: true

      - name: 'Run frontend tests'
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        uses: myparcelnl/actions/nx-run-many@v4
        with:
          target: 'test:coverage'
          args: '--parallel=1'

      - name: 'Move coverage files'
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        shell: bash
        #language=bash
        run: |
          yarn workspaces foreach -Ap --exclude . exec \
            bash -c 'if [ -f coverage/clover.xml ]; then mv coverage/clover.xml coverage/$(basename $(pwd)).xml; fi'

          find views -type f -name '*.xml' -exec bash -c 'mkdir -p coverage/$(dirname $1) && cp $1 coverage/$(dirname $1)/$(basename $1)' _ {} \;

      - uses: myparcelnl/actions/codecov-action@v4
        with:
          flags: unit,frontend,admin
          files: coverage/views/backend/*.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: myparcelnl/actions/codecov-action@v4
        with:
          flags: unit,frontend,checkout
          files: coverage/views/frontend/*.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: 'Cache coverage'
        uses: actions/cache@v4
        id: coverage-cache
        with:
          path: clover.xml
          key: coverage-backend-${{ hashFiles('**/composer.json', '**/composer.lock', 'src/**/*', 'tests/**/*') }}

      - uses: myparcelnl/actions/pdk-setup@v4
        id: setup
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        with:
          php-version: ${{ vars.PHP_VERSION }}
          composer-dev: 'true'

      - uses: myparcelnl/actions/pdk-upgrade@v4
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          report: 'false'
          no-check: true
          no-commit: true
          image: ${{ steps.setup.outputs.image }}

      - uses: myparcelnl/actions/composer-pest@v4
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        with:
          image: ${{ steps.setup.outputs.image }}

      - name: 'Fix coverage file'
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        shell: bash
        #language=bash
        run: |
          # Strip the /app/ prefix from the coverage paths before uploading.
          sed -i 's/\/app\///g' clover.xml

      - uses: myparcelnl/actions/codecov-action@v4
        with:
          flags: unit,backend
          files: clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
