name: '🔺 Upgrade PDK dependencies'

on:
  workflow_call:
    inputs:
      update-deps:
        description: 'This input is added to be able to depend on this workflow and still let dependent jobs run even if an upgrade is not requested.'
        type: boolean
        required: false
        default: true

      create-commit:
        description: 'Create a commit with the changes.'
        type: boolean
        required: false
        default: false

jobs:
  upgrade:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        if: inputs.update-deps == true

      - uses: myparcelnl/actions/pdk-setup-upgrade@v4
        if: inputs.update-deps == true
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          no-commit: ${{ github.event.inputs.create-commit != true }}
